using System;
namespace PanzerBlitz
{
	public enum UnitClass
	{
		WRECKAGE,
		TANK,
		ASSAULT_GUN,
		FLAME_TANK,
		SELF_PROPELLED_ARTILLERY,
		RECONNAISSANCE_VEHICLE,
		TRANSPORT,
		TOWED_GUN,
		INFANTRY,
		CAVALRY,
		AMPHIBIOUS_VEHICLE,
		ENGINEER_VEHICLE,
		FORT,
		BLOCK,
		MINEFIELD,
		OBSERVATION_AIRCRAFT,
		COMMAND_POST,
		BRIDGE
	}
}
