using System;
namespace PanzerBlitz
{
	public enum UnitClass
	{
		TANK,
		ASSAULT_GUN,
		FLAME_TANK,
		SELF_PROPELLED_ARTILLERY,
		RECONNAISSANCE_VEHICLE,
		TRANSPORT,
		TOWED_GUN,
		INFANTRY,
		CAVALRY,
		PARATROOP,
		COMMANDO,
		AMPHIBIOUS_VEHICLE,
		ENGINEER_VEHICLE,
		FORT,
		BLOCK,
		MINEFIELD,
		OBSERVATION_AIRCRAFT,
		FIGHTER_BOMBER,
		COMMAND_POST
	}
}
