namespace PanzerBlitz
{
	public enum ProgramState
	{
		BUILD_ARMY,
		BUILD_SCENARIO,
		EDIT,
		LANDING,
		LOCAL_MATCH_RECORD_SELECT,
		LOCAL_SCENARIO_SELECT,
		LOG_IN_PLAYER,
		MATCH,
		MATCH_END,
		MATCH_LOBBY,
		ONLINE_LANDING,
		REGISTER_PLAYER,
		SERVER
	}
}
